### ISSUE TITLE
Failure to identify diff in yaml

### ISSUE THREAD

**Issue by jDomantas** [Wilfred/difftastic#377]
File `test-old.yml`:

```yaml
key1:
- key2:
  {{ helm-expression }}
```

File `test-new.yml`:
```yaml
key1:
- key2:
  {{ helm-expression }}

new_key: yes
```

difft reports no diff:

```
$ difft test-old.yml test-new.yml
test-new.yml --- YAML
No syntactic changes.
```

difft version: 0.35.0
