### ISSUE TITLE
Lines added to yml show up as modifications of surrounding lines.

### ISSUE THREAD

**Issue by viraptor** [Wilfred/difftastic#422]
(1) A description of the issue. A screenshot is often helpful too.

![Screen Shot 2022-11-09 at 4 14 37 pm](https://user-images.githubusercontent.com/188063/200744516-339d6c8c-8ba6-4de1-8f54-f2cfb272105a.png)

I expected to see 2 lines added only and no changes around `foo-assets`.

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

first file (yml):
```
stacks:
  us-east-1:
    foo-assets:
      template: foo_assets.rb
    # foo-database-v2: # Commented out due to drift. See template for details.
    #   template: foo_database_v2.rb
    foo-database-security-group:
      template: security_group_single_port_access.rb
```
second file (yml)
```
stacks:
  us-east-1:
    foo-assets:
      template: foo_assets.rb
    foo-database-parameter-group:
      template: foo_database_parameter_group.rb
    # foo-database-v2: # Commented out due to drift. See template for details.
    #   template: foo_database_v2.rb
    foo-database-security-group:
      template: security_group_single_port_access.rb
```

It seems that removing the comment already messes it up.

(3) The version of difftastic you're using (see `difft --version`) and
your operating system.

0.27.0, running on darwin.
