### ISSUE TITLE
YAML files syntactic changes

### ISSUE THREAD

**Issue by tomasdedic** [Wilfred/difftastic#723]
When I **difft** two yaml files where only difference is position of element I am still getting diff change. 
I would expect it the be syntactically the same files.

![image](https://github.com/Wilfred/difftastic/assets/1618689/e82c104b-68b7-4217-8186-2b756f83af1e)

```shell
difft --version
Difftastic 0.57.0 (built with rustc 1.77.1)
difft cluster-monitoring-config.yaml cluster-monitoring-config2.yaml --check-only
cluster-monitoring-config2.yaml --- YAML
Has syntactic changes.
```

```yaml
#cluster-monitoring-config.yaml
apiVersion: v1
kind: ConfigMap
data:
  prometheusOperator:
    nodeSelector:
      node-role.kubernetes.io/worker: ''
  enableUserWorkload: true
  prometheusK8s:
    retention: 3d
    additionalAlertmanagerConfigs:
    - apiVersion: v2
      pathPrefix: /
      scheme: http
      timeout: "30s"
      tlsConfig:
        insecureSkipVerify: true
```
```yaml
#cluster-monitoring-config2.yaml
apiVersion: v1
kind: ConfigMap
data:
  enableUserWorkload: true
  prometheusOperator:
    nodeSelector:
      node-role.kubernetes.io/worker: ''
  prometheusK8s:
    retention: 3d
    additionalAlertmanagerConfigs:
    - apiVersion: v2
      pathPrefix: /
      scheme: http
      timeout: "30s"
      tlsConfig:
        insecureSkipVerify: true

```
